import json

with open('d:/ji-hyeon-hwang.github.io/deutsch/js/data_exam_vocab.js', 'r', encoding='utf-8') as f:
    content = f.read()

start = content.find('[')
end = content.rfind(']')
data = json.loads(content[start:end+1])

new_categories = [
    {
        "category_de": "Im Kaufhaus - Etagen (백화점 - 층별 안내)",
        "category_ko": "백화점 층별 매장",
        "items": [
            {"de": "das Erdgeschoss (EG)", "ko": "1층 (지상층)", "note": "독일에서는 지상층=0층 개념"},
            {"de": "das Untergeschoss (UG)", "ko": "지하층", "note": "UG = Untergeschoss"},
            {"de": "der erste Stock / 1. OG", "ko": "2층", "note": "OG = Obergeschoss"},
            {"de": "der zweite Stock / 2. OG", "ko": "3층", "note": ""},
            {"de": "die Rolltreppe / der Aufzug / der Fahrstuhl", "ko": "에스컬레이터 / 엘리베이터", "note": "Aufzug=Fahrstuhl 동의어"},
            {"de": "die Damenabteilung / die Damenmode", "ko": "여성복 코너 / 여성 패션", "note": ""},
            {"de": "die Herrenabteilung / die Herrenmode", "ko": "남성복 코너 / 남성 패션", "note": ""},
            {"de": "die Kinderabteilung / Kindermode", "ko": "아동복 코너", "note": ""},
            {"de": "die Babyabteilung / Babyartikel", "ko": "아기 용품 코너", "note": ""},
            {"de": "die Schuhabteilung", "ko": "신발 코너", "note": ""},
            {"de": "die Sportabteilung / Sportartikel", "ko": "스포츠 용품 코너", "note": ""},
            {"de": "die Elektroabteilung / Elektronik", "ko": "전자제품 코너", "note": "TV, Handy, Computer"},
            {"de": "die Haushaltsabteilung / Haushaltswaren", "ko": "주방/가정용품 코너", "note": ""},
            {"de": "die Möbelabteilung", "ko": "가구 코너", "note": ""},
            {"de": "die Bettwaren / Bettwäsche", "ko": "침구류", "note": ""},
            {"de": "die Lebensmittelabteilung", "ko": "식료품 코너", "note": "보통 지하"},
            {"de": "die Spielzeugabteilung / Spielwaren", "ko": "장난감 코너", "note": ""},
            {"de": "die Bücherabteilung / die Buchhandlung", "ko": "서적 코너 / 서점", "note": ""},
            {"de": "die Schmuckabteilung", "ko": "액세서리 / 보석 코너", "note": ""},
            {"de": "die Parfümerie / Kosmetik", "ko": "향수 / 화장품", "note": ""},
            {"de": "die Reisegepäck-Abteilung / Koffer und Taschen", "ko": "여행 가방 코너", "note": "Koffer = 캐리어"},
            {"de": "die Uhrenabteilung / Uhren und Schmuck", "ko": "시계 코너", "note": ""},
            {"de": "die Papeterie / Schreibwaren", "ko": "문구 코너", "note": ""},
            {"de": "die Feinkostabteilung", "ko": "델리 / 가공식품 코너", "note": ""},
            {"de": "die Getränkeabteilung", "ko": "음료 코너", "note": ""},
            {"de": "die Umkleidekabine", "ko": "탈의실", "note": ""},
            {"de": "die Kasse / an der Kasse", "ko": "계산대 / 계산대에서", "note": ""},
            {"de": "die Info / die Information", "ko": "안내 데스크", "note": ""},
            {"de": "das Fundbüro", "ko": "분실물 센터", "note": ""},
            {"de": "die Kundendienst / der Kundenservice", "ko": "고객 서비스", "note": ""},
            {"de": "die Toilette / das WC", "ko": "화장실", "note": "보통 각 층 또는 특정 층"},
            {"de": "die Kantine / das Restaurant / das Café", "ko": "구내식당 / 식당 / 카페", "note": "보통 위층"},
            {"de": "die Dachterrasse", "ko": "옥상 테라스", "note": ""},
            {"de": "der Parkplatz / die Tiefgarage", "ko": "주차장 / 지하 주차장", "note": ""}
        ]
    },
    {
        "category_de": "Behörden & Ausweise (관공서 / 신분증 관련)",
        "category_ko": "관공서 / 신분증",
        "items": [
            {"de": "der Ausweis / die Ausweise", "ko": "신분증", "note": "일반적 신분증"},
            {"de": "der Personalausweis", "ko": "주민등록증 (독일 신분증)", "note": "성인 필수"},
            {"de": "der Reisepass", "ko": "여권", "note": "해외 여행용"},
            {"de": "der Führerschein", "ko": "운전면허증", "note": ""},
            {"de": "die Aufenthaltserlaubnis / der Aufenthaltstitel", "ko": "체류 허가증", "note": "외국인 필수"},
            {"de": "das Visum / die Visa", "ko": "비자", "note": ""},
            {"de": "die Geburtsurkunde", "ko": "출생 증명서", "note": ""},
            {"de": "die Heiratsurkunde", "ko": "혼인 증명서", "note": ""},
            {"de": "die Meldebescheinigung", "ko": "거주지 등록증", "note": "독일 필수 서류"},
            {"de": "die Anmeldung / sich anmelden", "ko": "등록 / 등록하다", "note": "거주지 신고"},
            {"de": "die Abmeldung / sich abmelden", "ko": "거주지 이전 신고 / 해지", "note": ""},
            {"de": "das Bürgeramt / das Bürgerbüro", "ko": "시민청 / 주민센터", "note": "거주지 등록소"},
            {"de": "das Rathaus", "ko": "시청", "note": ""},
            {"de": "das Einwohnermeldeamt", "ko": "주민 등록 사무소", "note": ""},
            {"de": "die Ausländerbehörde", "ko": "외국인청", "note": "비자/체류 관련"},
            {"de": "das Finanzamt", "ko": "세무서", "note": ""},
            {"de": "die Steuernummer / die Steuer-ID", "ko": "세금 번호 / 세금 ID", "note": ""},
            {"de": "die Sozialversicherung / die Krankenkasse", "ko": "사회보험 / 건강보험", "note": ""},
            {"de": "das Formular / das Antragsformular", "ko": "양식 / 신청서", "note": "ausfüllen = 작성하다"},
            {"de": "der Antrag / einen Antrag stellen", "ko": "신청서 / 신청하다", "note": ""},
            {"de": "die Unterlagen / die Dokumente", "ko": "서류들", "note": "복수 사용"},
            {"de": "der Termin (beim Amt)", "ko": "관공서 예약", "note": "einen Termin vereinbaren"},
            {"de": "die Beglaubigung / beglaubigen", "ko": "공증 / 공증하다", "note": ""},
            {"de": "die Unterschrift / unterschreiben", "ko": "서명 / 서명하다", "note": ""},
            {"de": "gültig / ungültig", "ko": "유효한 / 무효한", "note": "gültig bis..."},
            {"de": "verlängern / die Verlängerung", "ko": "연장하다 / 연장", "note": "Pass verlängern"},
            {"de": "die Gebühr / die Bearbeitungsgebühr", "ko": "수수료 / 처리 수수료", "note": ""}
        ]
    },
    {
        "category_de": "Öffentliche Orte & Räume (공공 장소 / 시설)",
        "category_ko": "공공 장소 / 시설",
        "items": [
            {"de": "der Konferenzraum / der Besprechungsraum", "ko": "회의실", "note": "회사"},
            {"de": "das Wartezimmer / der Warteraum", "ko": "대기실", "note": "병원, 관공서"},
            {"de": "das Reisebüro", "ko": "여행사", "note": "여행 상담"},
            {"de": "die Reisebratung", "ko": "여행 상담실", "note": ""},
            {"de": "der Beratungsraum / die Beratung", "ko": "상담실 / 상담", "note": ""},
            {"de": "das Fotostudio / das Fotogeschäft", "ko": "사진관", "note": "여권/증명사진"},
            {"de": "das Passfoto / das Bewerbungsfoto", "ko": "여권사진 / 이력서용 사진", "note": ""},
            {"de": "das Sprechzimmer / die Praxis", "ko": "진료실 / 진료소", "note": "병원"},
            {"de": "der Empfang / die Rezeption", "ko": "접수처 / 리셉션", "note": ""},
            {"de": "das Klassenzimmer / der Kursraum", "ko": "교실 / 강의실", "note": ""},
            {"de": "die Aula", "ko": "강당", "note": ""},
            {"de": "der Hörsaal", "ko": "대형 강의실 (대학)", "note": ""},
            {"de": "die Mensa", "ko": "학생 식당", "note": "대학"},
            {"de": "die Kantine", "ko": "구내 식당", "note": "회사"},
            {"de": "der Pausenraum / die Pausenhalle", "ko": "휴게실 / 휴게공간", "note": ""},
            {"de": "das Büro / das Großraumbüro", "ko": "사무실 / 오픈오피스", "note": ""},
            {"de": "die Werkstatt", "ko": "작업실 / 정비소", "note": ""},
            {"de": "das Labor", "ko": "실험실", "note": ""},
            {"de": "der Sitzungssaal", "ko": "회의장", "note": "공식 회의"},
            {"de": "die Ausstellung / die Ausstellungshalle", "ko": "전시회 / 전시장", "note": ""},
            {"de": "das Messegelände", "ko": "박람회장", "note": ""},
            {"de": "das Schließfach", "ko": "물품 보관함 / 사물함", "note": "역, 수영장 등"},
            {"de": "die Garderobe", "ko": "옷 보관소", "note": "극장, 박물관 등"},
            {"de": "die Kirche / die Moschee / der Tempel", "ko": "교회 / 이슬람 사원 / 절", "note": ""},
            {"de": "der Friedhof", "ko": "묘지", "note": ""},
            {"de": "der Marktplatz", "ko": "시장 광장", "note": "구시가지 중심"},
            {"de": "der Springbrunnen", "ko": "분수", "note": "광장에 자주 있음"},
            {"de": "das Denkmal", "ko": "기념비", "note": ""}
        ]
    },
    {
        "category_de": "Reisen & Regionen (여행 / 지역)",
        "category_ko": "여행 / 지역 선택",
        "items": [
            {"de": "die Region / das Bundesland", "ko": "지역 / 주 (독일 연방주)", "note": "독일은 16개 주"},
            {"de": "Norddeutschland / Süddeutschland", "ko": "북독일 / 남독일", "note": ""},
            {"de": "die Alpen", "ko": "알프스", "note": ""},
            {"de": "die Nordsee / die Ostsee", "ko": "북해 / 발트해", "note": "독일 해변"},
            {"de": "der Bodensee", "ko": "보덴호", "note": "독일 최대 호수"},
            {"de": "der Schwarzwald", "ko": "흑림", "note": "남독일 유명 지역"},
            {"de": "das Meer / die Küste", "ko": "바다 / 해안", "note": ""},
            {"de": "die Insel / die Halbinsel", "ko": "섬 / 반도", "note": ""},
            {"de": "die Berge / das Gebirge", "ko": "산 (복수) / 산맥", "note": ""},
            {"de": "das Tal / die Ebene", "ko": "골짜기 / 평지", "note": ""},
            {"de": "der Fluss / der Bach", "ko": "강 / 시냇물", "note": ""},
            {"de": "das Dorf / das Kleinstadt / die Großstadt", "ko": "마을 / 작은 도시 / 큰 도시", "note": ""},
            {"de": "die Hauptstadt / die Landeshauptstadt", "ko": "수도 / 주도", "note": ""},
            {"de": "die Grenze", "ko": "국경", "note": ""},
            {"de": "das Ausland / im Ausland", "ko": "해외 / 해외에서", "note": ""},
            {"de": "das Inland", "ko": "국내", "note": ""},
            {"de": "die Pauschalreise / die Individualreise", "ko": "패키지 여행 / 개별 여행", "note": ""},
            {"de": "die Kreuzfahrt", "ko": "크루즈 여행", "note": ""},
            {"de": "die Wanderreise / der Wanderurlaub", "ko": "하이킹 여행", "note": ""},
            {"de": "der Städtetrip / die Städtereise", "ko": "도시 여행", "note": ""},
            {"de": "der Skiurlaub / der Winterurlaub", "ko": "스키 휴가 / 겨울 휴가", "note": ""},
            {"de": "der Strandurlaub / der Sommerurlaub", "ko": "해변 휴가 / 여름 휴가", "note": ""},
            {"de": "die Reisezeit / die Hauptsaison / die Nebensaison", "ko": "여행 시기 / 성수기 / 비수기", "note": ""},
            {"de": "die Reiseversicherung", "ko": "여행자 보험", "note": ""},
            {"de": "die Impfung", "ko": "예방 접종", "note": "해외 여행 전"}
        ]
    },
    {
        "category_de": "Baby & Kinder (아기 / 어린이 용품)",
        "category_ko": "아기 / 어린이 용품",
        "items": [
            {"de": "das Baby / das Kleinkind", "ko": "아기 / 유아", "note": ""},
            {"de": "der Kinderwagen / der Buggy", "ko": "유모차 / 접이식 유모차", "note": ""},
            {"de": "die Windel / die Windeln", "ko": "기저귀", "note": ""},
            {"de": "die Babyflasche / der Schnuller", "ko": "젖병 / 공갈젖꼭지", "note": ""},
            {"de": "die Babynahrung / das Baby-Essen", "ko": "이유식", "note": ""},
            {"de": "die Babykleidung / der Strampler", "ko": "아기 옷 / 우주복", "note": ""},
            {"de": "die Babyschuhe / der Lätzchen", "ko": "아기 신발 / 턱받이", "note": ""},
            {"de": "das Spielzeug / die Spielsachen", "ko": "장난감", "note": ""},
            {"de": "die Puppe / der Teddybär", "ko": "인형 / 곰인형", "note": ""},
            {"de": "das Bilderbuch / das Malbuch", "ko": "그림책 / 색칠 공부책", "note": ""},
            {"de": "die Bauklötze / das Bauspielzeug", "ko": "블록", "note": ""},
            {"de": "das Bett / das Kinderbett / das Babybett", "ko": "침대 / 아이 침대 / 아기 침대", "note": ""},
            {"de": "der Hochstuhl", "ko": "아기 의자 (식탁용)", "note": ""},
            {"de": "der Kindergarten / die Kita", "ko": "유치원 / 어린이집", "note": "Kita = Kindertagesstätte"},
            {"de": "die Krippe", "ko": "영아 보육 시설", "note": "3세 미만"},
            {"de": "der Kinderarzt / die Kinderärztin", "ko": "소아과 의사", "note": ""},
            {"de": "der Spielplatz / die Schaukel / die Rutsche", "ko": "놀이터 / 그네 / 미끄럼틀", "note": ""},
            {"de": "der Sandkasten", "ko": "모래놀이터", "note": ""},
            {"de": "der Kindersitz / der Autositz", "ko": "카시트", "note": "차량용"},
            {"de": "die Babypflege / die Babynahrungsabteilung", "ko": "아기 케어 / 아기 용품 코너", "note": "약국/마트"}
        ]
    },
    {
        "category_de": "Sicherheit & Notfall (안전 / 응급)",
        "category_ko": "안전 / 응급 상황",
        "items": [
            {"de": "der Notfall / im Notfall", "ko": "응급상황 / 응급상황에", "note": ""},
            {"de": "der Notausgang", "ko": "비상구", "note": ""},
            {"de": "der Feuerlöscher", "ko": "소화기", "note": ""},
            {"de": "der Rauchmelder", "ko": "화재 감지기", "note": ""},
            {"de": "die Feuerwehr / 112", "ko": "소방서 / 112", "note": "유럽 통합 응급번호"},
            {"de": "die Polizei / 110", "ko": "경찰 / 110", "note": "독일 경찰"},
            {"de": "der Krankenwagen", "ko": "구급차", "note": ""},
            {"de": "die Notaufnahme", "ko": "응급실", "note": ""},
            {"de": "der Erste-Hilfe-Kasten", "ko": "구급 상자", "note": ""},
            {"de": "das Pflaster / der Verband", "ko": "반창고 / 붕대", "note": ""},
            {"de": "vorsichtig / achtsam", "ko": "조심스러운 / 주의 깊은", "note": ""},
            {"de": "die Warnung / warnen", "ko": "경고 / 경고하다", "note": ""},
            {"de": "verboten / erlaubt", "ko": "금지된 / 허용된", "note": ""},
            {"de": "das Verbot / das Verbotsschild", "ko": "금지 / 금지 표지", "note": ""},
            {"de": "Rauchen verboten! / Nicht rauchen!", "ko": "흡연 금지!", "note": "표지"},
            {"de": "Betreten verboten!", "ko": "출입 금지!", "note": ""},
            {"de": "Achtung! / Vorsicht!", "ko": "주의! / 조심!", "note": ""},
            {"de": "Lebensgefahr!", "ko": "생명 위험!", "note": ""},
            {"de": "der Einbruch / einbrechen", "ko": "침입 / 침입하다", "note": ""},
            {"de": "der Diebstahl / stehlen", "ko": "도둑질 / 훔치다", "note": ""},
            {"de": "die Anzeige (bei Polizei) / anzeigen", "ko": "신고 / 신고하다", "note": ""},
            {"de": "verloren / gefunden", "ko": "잃어버린 / 찾은", "note": ""},
            {"de": "das Fundbüro", "ko": "분실물 센터", "note": "역, 백화점, 시청"}
        ]
    },
    {
        "category_de": "Öffentliche Verkehrsmittel (대중교통 상세)",
        "category_ko": "대중교통 세부 어휘",
        "items": [
            {"de": "der Fahrplan / der Zugfahrplan", "ko": "시간표 / 열차 시간표", "note": ""},
            {"de": "der Fahrkartenautomat", "ko": "티켓 자판기", "note": ""},
            {"de": "der Fahrkartenschalter", "ko": "매표소", "note": ""},
            {"de": "die Tageskarte / die Wochenkarte / die Monatskarte", "ko": "1일권 / 주간권 / 월간권", "note": ""},
            {"de": "die Einzelfahrkarte / die 4-Fahrten-Karte", "ko": "단일 승차권 / 4회권", "note": ""},
            {"de": "das Semesterticket", "ko": "학기 정기권", "note": "대학생용"},
            {"de": "die Ermäßigung / Studentenermäßigung / Seniorenermäßigung", "ko": "할인 / 학생/노인 할인", "note": ""},
            {"de": "der Zuschlag / der ICE-Zuschlag", "ko": "추가 요금 / ICE 추가요금", "note": ""},
            {"de": "der Schaffner / der Kontrolleur", "ko": "차장 / 검표원", "note": ""},
            {"de": "die Fahrkartenkontrolle", "ko": "표 검사", "note": ""},
            {"de": "das Schwarzfahren", "ko": "무임승차", "note": "벌금 있음"},
            {"de": "die 1. Klasse / die 2. Klasse", "ko": "1등석 / 2등석", "note": "기차"},
            {"de": "der Nichtraucherwagen / der Ruhewagen", "ko": "금연칸 / 조용한 칸", "note": ""},
            {"de": "der Speisewagen", "ko": "식당칸", "note": ""},
            {"de": "der Fensterplatz / der Gangplatz", "ko": "창가 자리 / 통로 자리", "note": ""},
            {"de": "die Reservierung / einen Platz reservieren", "ko": "예약 / 좌석 예약", "note": ""},
            {"de": "der Anschluss / verpassen", "ko": "환승편 / 놓치다", "note": "den Anschluss verpassen"},
            {"de": "der Umsteigebahnhof", "ko": "환승역", "note": ""},
            {"de": "die Endstation / die Endhaltestelle", "ko": "종점", "note": ""},
            {"de": "einsteigen / aussteigen / umsteigen", "ko": "타다 / 내리다 / 갈아타다", "note": "분리동사 + sein"},
            {"de": "der Bahnsteig / das Gleis", "ko": "플랫폼 / 선로", "note": ""},
            {"de": "der Schalter / das Reisezentrum", "ko": "창구 / 여행 센터", "note": "기차역"}
        ]
    },
    {
        "category_de": "Hotel & Übernachtung (호텔 / 숙박)",
        "category_ko": "호텔 / 숙박 상세",
        "items": [
            {"de": "das Hotel / das Motel / die Pension", "ko": "호텔 / 모텔 / 펜션", "note": ""},
            {"de": "die Jugendherberge", "ko": "유스호스텔", "note": ""},
            {"de": "die Ferienwohnung / das Ferienhaus", "ko": "휴가용 아파트 / 별장", "note": ""},
            {"de": "der Campingplatz", "ko": "캠핑장", "note": ""},
            {"de": "das Zelt / der Wohnwagen", "ko": "텐트 / 캠핑카", "note": ""},
            {"de": "das Einzelzimmer / das Doppelzimmer", "ko": "싱글룸 / 더블룸", "note": ""},
            {"de": "das Familienzimmer / die Suite", "ko": "패밀리룸 / 스위트룸", "note": ""},
            {"de": "das Zweibettzimmer", "ko": "트윈룸 (침대 2개)", "note": ""},
            {"de": "das Frühstücksbüfett / das Frühstück inklusive", "ko": "조식 뷔페 / 조식 포함", "note": ""},
            {"de": "die Halbpension / die Vollpension", "ko": "조식+석식 / 3식 포함", "note": ""},
            {"de": "die Übernachtung mit Frühstück (ÜF)", "ko": "숙박+조식", "note": ""},
            {"de": "der Zimmerservice", "ko": "룸서비스", "note": ""},
            {"de": "die Rezeption / einchecken / auschecken", "ko": "리셉션 / 체크인/아웃", "note": ""},
            {"de": "der Zimmerschlüssel / die Schlüsselkarte", "ko": "방 열쇠 / 카드키", "note": ""},
            {"de": "das WLAN / kostenloses WLAN", "ko": "와이파이 / 무료 와이파이", "note": ""},
            {"de": "der Fernseher / der Kühlschrank / der Safe", "ko": "TV / 냉장고 / 금고", "note": ""},
            {"de": "die Minibar", "ko": "미니바", "note": ""},
            {"de": "der Balkon mit Meerblick", "ko": "바다 전망 발코니", "note": ""},
            {"de": "das Schwimmbad / der Wellnessbereich / die Sauna", "ko": "수영장 / 웰니스 / 사우나", "note": ""},
            {"de": "der Parkplatz / die Tiefgarage", "ko": "주차장 / 지하 주차장", "note": ""},
            {"de": "der Aufpreis / der Nachlass", "ko": "추가 요금 / 할인", "note": ""},
            {"de": "die Stornierung / stornieren", "ko": "취소 / 취소하다", "note": ""},
            {"de": "die Kaution", "ko": "보증금", "note": ""},
            {"de": "der Zimmerpreis pro Nacht", "ko": "1박 가격", "note": ""}
        ]
    },
    {
        "category_de": "Restaurant & Bestellen (식당 / 주문)",
        "category_ko": "식당 / 주문 상세",
        "items": [
            {"de": "die Speisekarte / die Getränkekarte", "ko": "메뉴판 / 음료 메뉴", "note": ""},
            {"de": "das Menü / das Tagesmenü", "ko": "코스 메뉴 / 오늘의 메뉴", "note": ""},
            {"de": "die Vorspeise / die Hauptspeise / die Nachspeise", "ko": "전채 / 본식 / 후식", "note": ""},
            {"de": "die Suppe / der Salat", "ko": "수프 / 샐러드", "note": ""},
            {"de": "das Fleischgericht / das Fischgericht", "ko": "육류 요리 / 생선 요리", "note": ""},
            {"de": "das vegetarische Gericht / das vegane Gericht", "ko": "채식 요리 / 비건 요리", "note": ""},
            {"de": "die Beilage / die Beilagen", "ko": "곁들이 음식 / 사이드", "note": ""},
            {"de": "Pommes / Kartoffeln / Reis / Nudeln", "ko": "감자튀김 / 감자 / 밥 / 면", "note": "일반적 사이드"},
            {"de": "die Portion / eine kleine/große Portion", "ko": "1인분 / 작은/큰 사이즈", "note": ""},
            {"de": "das Kindermenü / für Kinder", "ko": "어린이 메뉴 / 어린이용", "note": ""},
            {"de": "der Tisch / einen Tisch reservieren", "ko": "테이블 / 자리 예약", "note": ""},
            {"de": "die Reservierung / eine Reservierung stornieren", "ko": "예약 / 예약 취소", "note": ""},
            {"de": "der Kellner / die Kellnerin / die Bedienung", "ko": "웨이터 / 웨이트리스 / 종업원", "note": ""},
            {"de": "bestellen / eine Bestellung aufgeben", "ko": "주문하다", "note": ""},
            {"de": "empfehlen / die Empfehlung des Hauses", "ko": "추천 / 오늘의 추천", "note": ""},
            {"de": "die Rechnung / getrennt oder zusammen", "ko": "계산서 / 각자 or 같이", "note": ""},
            {"de": "das Trinkgeld / Trinkgeld geben", "ko": "팁 / 팁 주기", "note": "보통 5-10%"},
            {"de": "die Serviette / das Besteck", "ko": "냅킨 / 식기", "note": "Besteck = Messer/Gabel/Löffel"},
            {"de": "das Messer / die Gabel / der Löffel", "ko": "칼 / 포크 / 숟가락", "note": ""},
            {"de": "der Teller / die Schüssel / die Tasse / das Glas", "ko": "접시 / 그릇 / 컵 / 유리컵", "note": ""},
            {"de": "die Öffnungszeiten / geöffnet / geschlossen", "ko": "영업시간 / 열림 / 닫힘", "note": ""},
            {"de": "Guten Appetit! / Zum Wohl! / Prost!", "ko": "맛있게 드세요! / 건배!", "note": "인사 표현"}
        ]
    },
    {
        "category_de": "Post & Bank (우체국 / 은행)",
        "category_ko": "우체국 / 은행",
        "items": [
            {"de": "die Post / das Postamt", "ko": "우체국", "note": ""},
            {"de": "der Brief / die Postkarte / das Paket", "ko": "편지 / 엽서 / 소포", "note": ""},
            {"de": "die Briefmarke / das Porto", "ko": "우표 / 우편요금", "note": ""},
            {"de": "der Umschlag", "ko": "봉투", "note": ""},
            {"de": "die Adresse / der Empfänger / der Absender", "ko": "주소 / 수신인 / 발신인", "note": ""},
            {"de": "die Postleitzahl (PLZ)", "ko": "우편번호", "note": ""},
            {"de": "das Einschreiben / die Sendungsverfolgung", "ko": "등기 / 배송 추적", "note": ""},
            {"de": "der Briefkasten / das Postfach", "ko": "우편함 / 사서함", "note": ""},
            {"de": "die Bank / die Sparkasse", "ko": "은행 / 저축은행", "note": ""},
            {"de": "das Konto / das Girokonto / das Sparkonto", "ko": "계좌 / 당좌 / 저축계좌", "note": ""},
            {"de": "ein Konto eröffnen / kündigen", "ko": "계좌 개설 / 해지", "note": ""},
            {"de": "die EC-Karte / die Kreditkarte", "ko": "체크카드 / 신용카드", "note": ""},
            {"de": "die Geheimzahl / die PIN", "ko": "비밀번호 / PIN", "note": ""},
            {"de": "der Geldautomat", "ko": "ATM", "note": ""},
            {"de": "Geld abheben / einzahlen", "ko": "돈 인출 / 입금", "note": "abheben=분리, einzahlen=분리"},
            {"de": "die Überweisung / überweisen", "ko": "송금 / 송금하다", "note": ""},
            {"de": "der Kontoauszug", "ko": "계좌 명세서", "note": ""},
            {"de": "der Kredit / einen Kredit aufnehmen", "ko": "대출 / 대출 받다", "note": ""},
            {"de": "die Zinsen / die Gebühren", "ko": "이자 / 수수료", "note": ""},
            {"de": "der Wechselkurs / Geld wechseln", "ko": "환율 / 환전하다", "note": ""},
            {"de": "der Kundenberater", "ko": "고객 상담사", "note": ""}
        ]
    }
]

data.extend(new_categories)

js_out = 'const EXAM_VOCAB = ' + json.dumps(data, ensure_ascii=False, indent=2) + ';\n'
with open('d:/ji-hyeon-hwang.github.io/deutsch/js/data_exam_vocab.js', 'w', encoding='utf-8') as f:
    f.write(js_out)

print(f"Categories: {len(data)}")
total_items = sum(len(c['items']) for c in data)
print(f"Total items: {total_items}")
